# Generated by Django 3.0.5 on 2024-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('4 Safa', '4 Safa'), ('5 Marwah', '5 Marwah'), ('5 Habsyah', '5 Habsyah'), ('6 Madinah', '6 Madinah'), ('6 Arafah', '6 Arafah')], default='4 Safa', max_length=10),
        ),
    ]
